### ISSUE TITLE
service-management闪退

### ISSUE THREAD

**Issue by wisdomtl** [tiann/understand-plugin-framework#14]
运行service-management时 发生如下异常
                                                 Process: com.weishu.upf.service_management.app, PID: 29732
                                                   java.lang.RuntimeException: Unable to instantiate application com.weishu.upf.service_management.app.UPFApplication: java.lang.RuntimeException: hook failed
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:608)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5165)
                                                       at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                       at android.os.Looper.loop(Looper.java:207)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5977)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
                                                    Caused by: java.lang.RuntimeException: hook failed
                                                       at com.weishu.upf.service_management.app.UPFApplication.attachBaseContext(UPFApplication.java:39)
                                                       at android.app.Application.attach(Application.java:199)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:993)
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:603)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5165) 
                                                       at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                       at android.os.Looper.loop(Looper.java:207) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5977) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)

**Comment by tiann** [comment]
> com.weishu.upf.service_management.app.UPFApplication.attachBaseContext(UPFApplication.java:39

把里面的错误打出来看看
